api/urls.py
"""URLConfig for api."""
from django.urls import path

from . import views

urlpatterns = [
    path("data_viz/", views.DataVizApiView.as_view()),
    path("ocr/<str:filename>", views.OcrApiView.as_view()),
    path("notification/", views.SendNotification.as_view()),
]

authentication/urls.py
"""Create your URL Routing for authentication here."""
from django.urls import path

from . import views

app_name = "auth"

urlpatterns = [
    path(
        "firebase_login",
        views.login,
        name="firebase_login",
    ),
    path(
        "firebase_register",
        views.register,
        name="firebase_register",
    ),
    path(
        "register",
        views.AuthenticationFormView.as_view(
            extra_context={"title": "Sign Up"},
        ),
        name="register",
    ),
    path(
        "login",
        views.AuthenticationFormView.as_view(
            extra_context={"title": "Sign In"},
        ),
        name="sign_in",
    ),
    path(
        "setup/<str:user_id>",
        views.AccountSetupFormView.as_view(
            extra_context={"title": "Account Setup"},
        ),
        name="setup",
    ),
    path("logout", views.logout, name="logout"),
    path(
        "forgot-password",
        views.ForgotPasswordFormView.as_view(
            extra_context={"title": "Forgot Password"},
        ),
        name="forgot_password",
    ),
    path(
        "lock-account",
        views.LockAccountFormView.as_view(
            extra_context={"title": "Lock Account"},
        ),
        name="lock_account",
    ),
]

one_barangay/urls.py
from django.urls import include, path, re_path
from django.views.decorators.cache import cache_control
from django.views.generic import TemplateView

urlpatterns = [
    path("ocr/", include("ocr.urls")),
    path("", include("app.urls")),
    path("dashboard", include("data_viz.urls")),
    path("", include("authentication.urls")),
    path("user_management/", include("user_management.urls")),
    path("user_profile/", include("user_profile.urls")),
    path("announcement/", include("announcement.urls")),
    path("bulk-sched/", include("bulk_sched.urls")),
    path("complaint/", include("complaint.urls")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    re_path(
        r"^service-worker.js",
        cache_control(max_age=2592000)(
            TemplateView.as_view(
                template_name="service-worker.js",
                content_type="application/javascript",
            )
        ),
        name="service-worker.js",
    ),
    path("appointment/", include("appointment.urls")),
    re_path(
        r"^firebase-messaging-sw.js",
        cache_control(max_age=2592000)(
            TemplateView.as_view(
                template_name="firebase-messaging-sw.js",
                content_type="application/javascript",
            )
        ),
        name="firebase-messaging-sw.js",
    ),
    path("api/", include("api.urls")),
]

authentication/models.py
"""Create your authentication models here."""
from firebase_admin import firestore
from google.api_core.exceptions import NotFound

from one_barangay.local_settings import logger
from one_barangay.settings import firebase_app


class AuthModel:
    """Class for firestore authentication database."""

    def __init__(self):
        """Initialize AuthModel attributes."""
        self.db = firestore.client(app=firebase_app)
        self.rbi_ref = self.db.collection("rbi")
        self.user_ref = self.db.collection("users")

    def connect_data_to_rbi(self, user_data: dict) -> bool:
        """Associate authentication and rbi data.

        Args:
          user_data: The data of the user.

        Returns:
          Boolean True if the rbi of authenticated user exists, False if not.
        """
        try:
            doc = (
                self.rbi_ref.where(
                    f"family_members.{user_data['first_name']}.last_name",
                    "==",
                    user_data["last_name"],
                )
                .limit(1)
                .get()[0]
            )

            if doc.exists:
                self.rbi_ref.document(doc.id).update(
                    {
                        f"family_members.{user_data['first_name']}.uid": user_data["uid"],
                        f"family_members.{user_data['first_name']}.email": user_data["email"],
                        f"family_members.{user_data['first_name']}.photo": user_data["photo"]
                        if user_data.get("photo")
                        else user_data.get("photo_url"),
                        f"family_members.{user_data['first_name']}.phone_number": user_data["phone_number"],
                    }
                )
                logger.info(
                    "[AuthModel.connect_auth_to_rbi] User %s created in rbi collection.",
                    user_data["uid"],
                )
                return True
            else:
                logger.warning(
                    "[AuthModel.connect_auth_to_rbi] User %s NOT in rbi collection.",
                    user_data["uid"],
                )
                return False
        except IndexError as e:
            logger.exception(
                "[AuthModel.connect_auth_to_rbi] User %s not found in rbi collection. %s",
                user_data["uid"],
                e,
            )
            return False
        except NotFound as e:
            logger.exception(
                "[AuthModel.connect_auth_to_rbi] User %s not found in rbi collection. %s",
                user_data["uid"],
                e,
            )
            return False
        except TypeError as e:
            logger.exception("Something went wrong. %s", e)
            raise TypeError("Something went wrong.") from e

    def store_user_data(self, uid: str, user_data: dict) -> bool:
        """Store user data in users collection.

        Args:
          uid: The user id of the authenticated user.
          user_data: The data of the authenticated user.

        Returns:
          None.
        """
        try:
            user_data["updated_on"] = firestore.SERVER_TIMESTAMP
            self.user_ref.document(uid).set(user_data, merge=True)
            logger.info("[AuthModel.store_user_data] User %s created in firestore users collection.", uid)
            return True
        except IndexError as e:
            logger.exception("[AuthModel.store_user_data] User %s not created. %s", uid, e)
            return False
        except NotFound as e:
            logger.exception("[AuthModel.store_user_data] User %s not created. %s", uid, e)
            return False
        except TypeError as e:
            logger.exception("[AuthModel.store_user_data] Something went wrong. %s", e)
            raise TypeError("[AuthModel.store_user_data] Something went wrong.") from e

    def update_user_data(self, uid: str, user_data: dict) -> bool:
        """Update user data from firestore users collection.

        Args:
          uid: The user id of the authenticated user.
          user_data: The data of the authenticated user.

        Returns:
          None.
        """
        try:
            user_data["updated_on"] = firestore.SERVER_TIMESTAMP
            self.user_ref.document(uid).update(user_data)
            return True
        except NotFound as e:
            logger.exception("User Not Found. %s", e)
            return False
        except TypeError as e:
            logger.exception("Something went wrong. %s", e)
            return False

authentication/forms.py
"""Create your authentication forms here."""
from django import forms
from django.core.validators import RegexValidator

from one_barangay.widgets import DatePickerWidget


class AccountSetupForm(forms.Form):
    """Forgot Password Form."""

    error_css_class = "is-invalid"
    required_css_class = "required"

    phone_regex = RegexValidator(
        regex=r"^\+?1?\d{9,15}$",
        message="Phone number must be entered in the format: \
                    '+999999999'. Up to 15 digits allowed.",
    )
    contact_number = forms.CharField(
        validators=[phone_regex],
        help_text="Not required but highly recommended!",
        label="Phone Number",
        required=False,
        label_suffix="",
        max_length=17,
        widget=forms.TextInput(
            attrs={
                "placeholder": "+631234567891",
                "class": "",
                "type": "tel",
                "pattern": r"^\+?1?\d{9,15}$",
            }
        ),
    )
    placeholder = "Room/Floor/Unit #. Bldg Name, House Lot/Block, Street, Subdivision"
    address = forms.CharField(
        widget=forms.HiddenInput(
            attrs={
                "class": "",
                "placeholder": placeholder,
            }
        )
    )
    street = forms.CharField(widget=forms.HiddenInput(attrs={"class": ""}))
    zip_code = forms.CharField(widget=forms.HiddenInput(attrs={"class": ""}))
    country = forms.CharField(widget=forms.HiddenInput(attrs={"class": ""}))
    province = forms.CharField(widget=forms.HiddenInput(attrs={"class": ""}))
    city = forms.CharField(widget=forms.HiddenInput(attrs={"class": ""}))
    barangay = forms.CharField(widget=forms.HiddenInput(attrs={"class": ""}))
    region = forms.CharField(widget=forms.HiddenInput(attrs={"class": ""}))

    longitude = forms.CharField(widget=forms.HiddenInput(attrs={"class": ""}))
    latitude = forms.CharField(widget=forms.HiddenInput(attrs={"class": ""}))

    first_name = forms.CharField(
        label="First Name",
        label_suffix="",
        widget=forms.TextInput(attrs={"class": ""}),
    )
    middle_name = forms.CharField(
        label="Middle Name",
        label_suffix="",
        required=False,
        widget=forms.TextInput(attrs={"class": ""}),
    )
    last_name = forms.CharField(
        label="Last Name",
        label_suffix="",
        widget=forms.TextInput(attrs={"class": ""}),
    )
    date_of_birth = forms.DateField(
        label="Birth Date",
        label_suffix="",
        input_formats=[
            "%Y-%m-%d",
            "%m/%d/%Y",
            "%m/%d/%y",
            "%b %d %Y",
            "%b %d, %Y",
            "%d %b %Y",
            "%d %b, %Y",
            "%B %d %Y",
            "%B %d, %Y",
            "%d %B %Y",
            "%d %B, %Y",
            "%A, %b, %d %Y",
        ],
        widget=DatePickerWidget(attrs={"class": "date-picker", "autocomplete": "off"}),
    )
    birth_place = forms.CharField(
        label="Birth Place",
        label_suffix="",
        widget=forms.TextInput(attrs={"class": ""}),
    )

    def __init__(self, *args, **kwargs):
        """Initialize AccountSetupForm form field value."""
        super().__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs["class"] += " form-control text-black"

        # for field in self.hidden_fields():
        #     field_name = field.html_name
        #     if field_name not in ["country", "latitude", "longitude"]:
        #         self.fields[field_name].widget.attrs["class"] += " hidden_el"


class ForgotPasswordForm(forms.Form):
    """Forgot Password Form."""

    error_css_class = "is-invalid"
    required_css_class = "required"

    email = forms.EmailField(
        label="Your Email",
        label_suffix="",
        widget=forms.EmailInput(
            attrs={
                "placeholder": "juan_delacruz@gmail.com",
                "class": "form-control",
                "autofocus": True,
            }
        ),
    )


class LockAccountForm(forms.Form):
    """Lock Account Form."""

    error_css_class = "is-invalid"
    required_css_class = "required"

    password = forms.CharField(
        label="Your Password",
        label_suffix="",
        min_length=8,
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password",
                "class": "form-control",
                "pattern": r"^\S{8,}$",
                "onchange": "this.setCustomValidity(this.validity.patternMismatch ? "
                "'Must have at least 8 characters' : ''); "
                "if(this.checkValidity()) form.confirm_password.pattern = this.value;",
                "oninput": "password.setCustomValidity("
                "password.value !== confirm_password.value ? "
                "'Password is not the same with the confirm password.' : '')",
            }
        ),
    )

    def clean_password(self):
        """Clean password for minimum length."""
        cleaned_data = super().clean()
        password = cleaned_data.get("password")

        if len(password) < 8:
            raise forms.ValidationError("The minimum password length is 8 characters.")

        return cleaned_data


class AuthenticationForm(LockAccountForm, ForgotPasswordForm):
    """Login, Signup and Forgot Password Form."""

    error_css_class = "is-invalid"
    required_css_class = "required"

    confirm_password = forms.CharField(
        label="Confirm Password",
        label_suffix="",
        min_length=8,
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Re-type Password",
                "class": "form-control",
                "pattern": r"^\S{8,}$",
                "onchange": "this.setCustomValidity(this.validity.patternMismatch ? "
                "'Please enter the same Password as above' : '');",
            }
        ),
    )
    remember_me = forms.BooleanField(
        label="Remember Me",
        label_suffix="",
        widget=forms.CheckboxInput(attrs={"class": "form-check-input"}),
    )
    terms_condition = forms.BooleanField(
        widget=forms.CheckboxInput(attrs={"class": "form-check-input"}),
    )

    def clean(self):
        """Customize cleaning for form fields."""
        cleaned_data = super().clean()

        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if (password and confirm_password) and (password != confirm_password):
            raise forms.ValidationError("Password and Confirm Password do not match.")

        return cleaned_data

authentication/templates/authentication/account_setup.html
{% extends "layouts/base-fullscreen.html" %}
{% block title %}{{ title }}{% endblock %}
{% load static %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
    {{ form.media.css }}
{% endblock stylesheets %}

{% block content %}
    <section class="vh-lg-100 mt-5 mt-lg-0 bg-soft d-flex align-items-center">
        <div class="container">
            <div class="row justify-content-center form-bg-image img-fluid w-100" data-background-lg="{% static "/assets/img/illustrations/signin.svg" %}">
                <div class="col-12 d-flex align-items-center justify-content-center">
                    <div class="bg-white shadow border-0 rounded border-light p-4 p-lg-5 fmxw-500">
                        <div class="text-center text-md-center mb-4 mt-md-0">
                            <h1 class="mb-0 h3">
                                oneBarangay - {{ title }}
                            </h1>
                            <br/>
                            <p>Let's Setup Your Account!</p>
                            {% if form.non_field_errors %}
                                <div class="alert alert-danger" role="alert">
                                    {% for error in form.non_field_errors %}
                                        <p class="text-center">{{ error }}</p>
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>

                        <form method="post" id="setup-form">
                            {% csrf_token %}
                            {% for field in form.hidden_fields %}
                                {% if field.html_name in hidden_fields %}
                                    {{ field }}
                                {% endif %}
                            {% endfor %}

                            <div class="row mb-4">
                                {% for field in form.visible_fields %}
                                    {% if field.html_name in first_row %}
                                        <div class="form-group col">
                                            {{ field.label_tag }}
                                            {{ field }}
                                            <small class="form-text text-muted d-block">{{ field.help_text }}</small>
                                            {% if form.event.errors %}
                                                {% if field.errors %}
                                                    <div class="badge m-0 bg-danger text-uppercase">{{ field.errors|striptags }}</div>
                                                {% endif %}
                                            {% endif %}
                                        </div>
                                    {% endif %}
                                {% endfor %}
                            </div>

                            {% for field in form.visible_fields %}
                                <div class="form-group mb-4">
                                    {% if field.html_name not in row_fields %}
                                        {{ field.label_tag }}
                                        {{ field }}
                                        <small class="form-text text-muted d-block">{{ field.help_text }}</small>
                                        {% if field.errors %}
                                            <div class="badge m-0 bg-danger text-uppercase">{{ field.errors|striptags }}</div>
                                        {% endif %}
                                    {% endif %}
                                </div>
                            {% endfor %}

                            <!-- Address -->
                            <div class="form-group mb-4">
                                <label for="id-google-address" class="required">Address</label>
                                <input class="form-control text-black" type="text" placeholder="*Begin typing address" id="id-google-address" name="google_address" required>
                            </div>

                            <!-- Address -->
                            <div class="form-group mb-4">
                                <label class="col-form-label text-nowrap hidden-el {% if form.address.field.required %}required{% endif %}" for="{{ form.address.auto_id }}" hidden>
                                    {{ form.address.label }}
                                </label>
                                {{ form.address }}
                            </div>

                            <div class="row hidden_el">
                                {% for field in form.hidden_fields %}
                                    {% if field.html_name in first_address %}
                                        <div class="form-group col">
                                            <label class="col-form-label text-nowrap hidden-el {% if field.field.required %}required{% endif %}" for="{{ field.auto_id }}" hidden>
                                                {{ field.label }}
                                            </label>
                                            {{ field }}
                                            <small class="form-text text-muted d-block">{{ field.help_text }}</small>
                                            {% if form.event.errors %}
                                                {% if field.errors %}
                                                    <div class="badge m-0 bg-danger text-uppercase">{{ field.errors|striptags }}</div>
                                                {% endif %}
                                            {% endif %}
                                        </div>
                                    {% endif %}
                                {% endfor %}
                            </div>

                            <div class="row mb-4">
                                {% for field in form.hidden_fields %}
                                    {% if field.html_name in second_address %}
                                        <div class="form-group col hidden_el">
                                            <label class="col-form-label text-nowrap hidden-el {% if field.field.required %}required{% endif %}" for="{{ field.auto_id }}" hidden>
                                                {{ field.label }}
                                            </label>
                                            {{ field }}
                                            <small class="form-text text-muted d-block">{{ field.help_text }}</small>
                                            {% if form.event.errors %}
                                                {% if field.errors %}
                                                    <div class="badge m-0 bg-danger text-uppercase">{{ field.errors|striptags }}</div>
                                                {% endif %}
                                            {% endif %}
                                        </div>
                                    {% endif %}
                                {% endfor %}
                            </div>
                            <!-- End of Address -->

                            <div class="row mb-4">
                                {% for field in form.visible_fields %}
                                    {% if field.html_name in second_row %}
                                        <div class="form-group col">
                                            {{ field.label_tag }}
                                            {{ field }}
                                            <small class="form-text text-muted d-block">{{ field.help_text }}</small>
                                            {% if form.event.errors %}
                                                {% if field.errors %}
                                                    <div class="badge m-0 bg-danger text-uppercase">{{ field.errors|striptags }}</div>
                                                {% endif %}
                                            {% endif %}
                                        </div>
                                    {% endif %}
                                {% endfor %}
                            </div>
                        </form>
                        <div class="text-center mt-4">
                            <!-- FIXME: Reset button not working -->
                            <button type="reset" form="setup-form" id="reset-btn" class="btn btn-secondary" hidden>Reset</button>
                            <button type="submit" form="setup-form" id="submit-btn" class="btn btn-primary" hidden>Submit</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

{% block scripts %}
    {{ form.media.js }}
    <script type="text/javascript">
        const google_api_key = "{{google_api_key|safe}}";
    </script>
    <script src="{% static "/assets/js/google_places.js" %}"></script>
    <script>
        $('#id_date_of_birth').datetimepicker({
            format: 'F d, Y',
            timepicker: false
        });
    </script>
    <script>
        {% if messages %}
            {% for message in messages %}
                {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                    Swal.fire({
                        title: 'Success',
                        icon: 'success',
                        text: '{{ message }}',
                    })
                {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                    Swal.fire({
                        title: 'Error!',
                        icon: 'error',
                        text: '{{ message }}',
                    })
                {% elif message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
                    Swal.fire({
                        title: 'NOTE!',
                        icon: 'info',
                        text: '{{ message }}',
                    })
                {% endif %}
            {% endfor %}
        {% endif %}
    </script>
{% endblock scripts %}

authentication/templates/authentication/forgot_password.html
{% extends "layouts/base-fullscreen.html" %}
{% block title %}{{ title }}{% endblock %}
{% load static %}

{% block content %}
    <main>
        <section class="vh-lg-100 mt-5 mt-lg-0 bg-soft d-flex align-items-center">
            <div class="container">
                <div class="row justify-content-center form-bg-image" data-background-lg="{% static "/assets/img/illustrations/signin.svg" %}">
                    <p class="text-center">
                        <a href="{% url "auth:sign_in" %}" class="d-flex align-items-center justify-content-center">
                            <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                                <path
                                    fill-rule="evenodd"
                                    d="M7.707 14.707a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l2.293 2.293a1 1 0 010 1.414z"
                                    clip-rule="evenodd"
                                ></path>
                            </svg>
                            Back to log in
                        </a>
                    </p>
                    <div class="col-12 d-flex align-items-center justify-content-center">
                        <div class="signin-inner my-3 my-lg-0 bg-white shadow border-0 rounded p-4 p-lg-5 w-100 fmxw-500">
                            <h1 class="h3">Forgot your password?</h1>
                            <p class="mb-4">Don't fret! Just type in your email and we will send you a code to reset your password!</p>
                            <form method="post" action="#">
                                {% csrf_token %}

                                <!-- Form -->
                                <div class="mb-4">
                                    {{ form.email.label_tag }}
                                    <div class="input-group">
                                        {{ form.email }}
                                    </div>
                                    <div class="invalid-feedback">{{ form.email.errors|striptags }}</div>
                                </div>
                                <!-- End of Form -->

                                <div class="d-grid">
                                    <button type="submit" class="btn btn-gray-800">Recover password</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block scripts %}
    <script>
        const swalWithBootstrapButtons = Swal.mixin({
            customClass: {
                confirmButton: 'btn btn-success',
                cancelButton: 'btn btn-danger me-2'
            },
            buttonsStyling: false
        })
        {% if messages %}
            {% for message in messages %}
                {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                    swalWithBootstrapButtons.fire({
                        title: 'Password reset Successfully!',
                        text: {{ message }},
                        icon: 'success',
                        confirmButtonText: 'Reset password',
                    }).then((result) => {
                        if (result.isConfirmed) {
                            window.open('{{ reset_link }}','_blank');
                            window.location.href = "/login"
                        }
                    });
                {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                    Swal.fire(
                        'Error!',
                        `Something went wrong.`,
                        'error',
                    );
                {% endif %}
            {% endfor %}
        {% endif %}
    </script>
{% endblock scripts %}