api/urls.py
"""URLConfig for api."""
from django.urls import path

from . import views

urlpatterns = [
    path("data_viz/", views.DataVizApiView.as_view()),
    path("ocr/<str:filename>", views.OcrApiView.as_view()),
    path("notification/", views.SendNotification.as_view()),
]

appointment/urls.py
"""URL Routing for Appointment."""
from django.urls import path

from . import views

app_name = "appointment"


# class DateConverter:
#     regex = "\d{4}-\d{2}-\d{2}"
#
#     def to_python(self, value):
#         return datetime.datetime.strptime(value, "%Y-%m-%d")
#
#     def to_url(self, value):
#         return value
#
#
# register_converter(DateConverter, "yyyy")

urlpatterns = [
    path("document/request/", views.document_request, name="document_request"),
    path("document/my-request/", views.my_document_request, name="my_document_request"),
    path(
        "user/document/schedule/<str:document_id>",
        views.appointment_schedule,
        name="appointment_schedule",
    ),
    path(
        "user/verification/<str:document_id>",
        views.user_document_verification,
        name="user_document_verification",
    ),
    path(
        "user/document/cancel/",
        views.user_document_cancel,
        name="document_cancel",
    ),
    path(
        "user/document/cancel/<str:document_id>",
        views.user_document_cancel,
        name="document_cancel",
    ),
    path(
        "user/dummy/appointment",
        views.add_document_request,
        name="add_document_request",
    ),
    path(
        "user/document/request/verified/<str:document_request_id>",
        views.user_document_verification,
        name="document_request_verified",
    ),
    path(
        "user/document/issuing/list/<str:document_id>",
        views.user_issuing_list,
        name="user_issuing_list",
    ),
    path(
        "user/document/issuing/success/<str:document_id>/<str:document_slugify>",
        views.document_issuing_success,
        name="document_issuing_success",
    ),
    path(
        "user/document/issuing/process/<str:document_id>/<str:document_slugify>",
        views.docu_issue_process,
        name="docu_issue_process",
    ),
    path(
        "user/document/issuing/update/<str:document_id>/<str:document_slugify>",
        views.request_update_document,
        name="request_update_document",
    ),
    path(
        "user/document/request/verification/<str:document_id>",
        views.user_verification_dt,
        name="user_verification_dt",
    ),
    path(
        "user/verification/selection/<str:document_request_id>",
        views.user_selection_data,
        name="user_selection_data",
    ),
    path(
        "user/document/info/<str:document_id>/<str:document_slugify>",
        views.document_input_info,
        name="document_input_info",
    ),
    path(
        "user/document/process/status/<str:document_request_id>",
        views.document_process_change_status,
        name="document_process_change_status",
    ),
    path("user/document/request", views.request_document, name="request_document"),
    path(
        "queueing/list",
        views.appointment_query_list,
        name="appointment_query_list",
    ),
    path(
        "user/view/appointment/<str:document_id>",
        views.view_appointment,
        name="view_appointment",
    ),
    path(
        "user/document/view/<str:document_id>/<str:document_slugify>",
        views.view_document_page,
        name="view_document_page",
    ),
    path(
        "user/document/store/data/<str:document_id>/<str:document_slugify>",
        views.docu_input_info,
        name="docu_input_info",
    ),
    path(
        "user/document/edit/<str:document_id>/<str:document_slugify>",
        views.apt_edit_docu,
        name="apt_edit_docu",
    ),
    path(
        "user/update/appointment/document/<str:document_id>/<str:document_slugify>",
        views.appointment_update_document,
        name="appointment_update_document",
    ),
    path(
        "user/document/reschedule/<str:appointment_id>",
        views.reschedule_appointment,
        name="reschedule_appointment",
    ),
    path(
        "user/document/complete/<str:appointment_id>",
        views.appointment_complete,
        name="appointment_complete",
    ),
    path(
        "user/appointment/cancel/<str:document_id>",
        views.appointment_cancel,
        name="appointment_cancel",
    ),
]

one_barangay/urls.py
from django.urls import include, path, re_path
from django.views.decorators.cache import cache_control
from django.views.generic import TemplateView

urlpatterns = [
    path("ocr/", include("ocr.urls")),
    path("", include("app.urls")),
    path("dashboard", include("data_viz.urls")),
    path("", include("authentication.urls")),
    path("user_management/", include("user_management.urls")),
    path("user_profile/", include("user_profile.urls")),
    path("announcement/", include("announcement.urls")),
    path("bulk-sched/", include("bulk_sched.urls")),
    path("complaint/", include("complaint.urls")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    re_path(
        r"^service-worker.js",
        cache_control(max_age=2592000)(
            TemplateView.as_view(
                template_name="service-worker.js",
                content_type="application/javascript",
            )
        ),
        name="service-worker.js",
    ),
    path("appointment/", include("appointment.urls")),
    re_path(
        r"^firebase-messaging-sw.js",
        cache_control(max_age=2592000)(
            TemplateView.as_view(
                template_name="firebase-messaging-sw.js",
                content_type="application/javascript",
            )
        ),
        name="firebase-messaging-sw.js",
    ),
    path("api/", include("api.urls")),
]

appointment/forms.py
"""Appointment forms."""
from django import forms
from django.forms import fields

from one_barangay.widgets import DatePickerWidget

document_list = [
    ("barangay-certificate", "Barangay Certificate"),
    ("barangay-clearance", "Barangay Clearance"),
    # ("barangay-cedula", "Barangay Cedula"),
    ("barangay-local-employment", "Barangay Local Employment"),
    ("barangay-verification", "Barangay Verification"),
    ("certificate-of-indigency", "Certificate of Indigency"),
]


class AppointmentVerifyUser(forms.Form):
    """ID Verification class."""

    first_name = forms.CharField(max_length=50)
    middle_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)


class BarangayCertificate(forms.Form):
    """Class for Barangay Certificate."""

    date = fields.DateField(widget=forms.widgets.DateInput(attrs={"type": "date"}))
    fullname = forms.CharField(label="Fullname", max_length=100, min_length=2, required=True)
    address = forms.CharField(label="Address", max_length=200, required=True)
    year = forms.CharField(label="Enter year of residency", max_length=4, min_length=4, required=True)
    issued = forms.CharField(label="Issued for", required=True)
    conforme = forms.CharField(label="Conforme", required=True)
    ctc = forms.CharField(label="CTC No.", max_length=15, required=True)
    region = forms.CharField(label="Region", required=True)
    orno = forms.CharField(label="OR No.", required=True)
    amount = forms.DecimalField(label="Amount", decimal_places=2, required=True)
    valid = fields.DateField(widget=forms.widgets.DateInput(attrs={"type": "date"}))
    prepared = forms.CharField(label="Prepared by", required=True)


class BarangayClearance(forms.Form):
    """Class for Barangay Clearance."""

    date = fields.DateField(widget=forms.widgets.DateInput(attrs={"type": "date"}))
    fullname = forms.CharField(label="Fullname", max_length=100, min_length=2, required=True)
    address = forms.CharField(label="Address", max_length=200, required=True)
    year = forms.CharField(label="Enter year of residency", max_length=4, min_length=4, required=True)
    issued = forms.CharField(label="Issued for", required=True, initial="Clearance")
    conforme = forms.CharField(label="Conforme", required=True)
    ctc = forms.CharField(label="CTC No.", max_length=15, required=True)
    region = forms.CharField(label="Region", required=True)
    orno = forms.CharField(label="OR No.", required=True)
    amount = forms.DecimalField(label="Amount", decimal_places=2, required=True)
    valid = fields.DateField(widget=forms.widgets.DateInput(attrs={"type": "date"}))
    prepared = forms.CharField(label="Prepared by", required=True)


class BarangayIndigency(forms.Form):
    """Class for Barangay Indigency."""

    date = fields.DateField(widget=forms.widgets.DateInput(attrs={"type": "date"}))
    fullname = forms.CharField(label="Fullname", max_length=100, min_length=2, required=True)
    address = forms.CharField(label="Address", max_length=200, required=True)
    year = forms.CharField(label="Enter year of residency", max_length=4, min_length=4, required=True)
    purpose = forms.CharField(label="Purpose", required=True)
    recipient = forms.CharField(label="Recipient", required=True)
    conforme = forms.CharField(label="Conforme", required=True)
    ctc = forms.CharField(label="CTC No.", max_length=15, required=True)
    region = forms.CharField(label="Region", required=True)
    valid = fields.DateField(widget=forms.widgets.DateInput(attrs={"type": "date"}))
    prepared = forms.CharField(label="Prepared by", required=True)


class BarangayLocalEmployment(forms.Form):
    """Class for Barangay Local Employment."""

    date = fields.DateField(widget=forms.widgets.DateInput(attrs={"type": "date"}))
    fullname = forms.CharField(label="Fullname", max_length=100, min_length=2, required=True)
    address = forms.CharField(label="Address", max_length=200, required=True)
    year = forms.CharField(label="Enter year of residency", max_length=4, min_length=4, required=True)
    conforme = forms.CharField(label="Conforme", required=True)
    ctc = forms.CharField(label="CTC No.", max_length=15, required=True)
    region = forms.CharField(label="Region", required=True)
    orno = forms.CharField(label="OR No.", required=True)
    amount = forms.DecimalField(label="Amount", decimal_places=2, required=True)
    valid = fields.DateField(widget=forms.widgets.DateInput(attrs={"type": "date"}))
    prepared = forms.CharField(label="Prepared by", required=True)


class BarangayVerification(forms.Form):
    """Class for Barangay Local Employment."""

    date = fields.DateField(widget=forms.widgets.DateInput(attrs={"type": "date"}))
    fullname = forms.CharField(label="Fullname", max_length=100, min_length=2, required=True)
    address = forms.CharField(label="Address", max_length=200, required=True)
    year = forms.CharField(label="Enter year of residency", max_length=4, min_length=4, required=True)
    conforme = forms.CharField(label="Conforme", required=True)
    ctc = forms.CharField(label="CTC No.", max_length=15, required=True)
    region = forms.CharField(label="Region", required=True)
    orno = forms.CharField(label="OR No.", required=True)
    amount = forms.DecimalField(label="Amount", decimal_places=2, required=True)
    valid = fields.DateField(widget=forms.widgets.DateInput(attrs={"type": "date"}))
    prepared = forms.CharField(label="Prepared by", required=True)


class DocumentSelection(forms.Form):
    """Class for Document Selection."""

    document = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple, choices=document_list)

    purpose = forms.CharField(widget=forms.Textarea(attrs={"name": "purpose", "rows": "3", "col": "5"}))

    verification = forms.ImageField(
        label_suffix="",
        label="Upload your ID",
        widget=forms.ClearableFileInput(attrs={"class": "form-control", "multiple": False}),
    )


class Appointment(forms.Form):
    """Class Appointment."""

    date = forms.DateTimeField(
        label="Date",
        input_formats=[
            "%Y-%m-%d",
            "%m/%d/%Y %I:%M",
            "%Y/%m/%d %H:%M",
            "%m/%d/%y",
            "%b %d %Y",
            "%b %d, %Y",
            "%d %b %Y",
            "%d %b, %Y",
            "%B %d %Y",
            "%B %d, %Y",
            "%d %B %Y",
            "%d %B, %Y",
        ],
        widget=DatePickerWidget(
            attrs={"class": "form-control", "autocomplete": "off"},
        ),
    )

appointment/templates/appointment/document_request.html
{% extends "layouts/base.html" %}

{% load static %}

{% block title %}
    Barangay Admin - Document Requests
{% endblock %}

{% block stylesheets %}
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="https://unpkg.com/@popperjs/core@2"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.11.3/js/dataTables.bootstrap5.min.js"></script>
    <link href="https://netdna.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://netdna.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>
    <link href="https://cdn.datatables.net/1.11.3/css/dataTables.bootstrap5.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/css/bootstrap.min.css" rel="stylesheet">

    <link href="{% static "appointment/assets/css/document_request.css" %}" rel="stylesheet">
{% endblock %}

{#{% block back_button %}#}
{#    <div class="mb-1">#}
{#        <a class="btn-back text-dark" href="{% url "services:index" %}"><--Go back to services</a>#}
{#    </div>#}
{#{% endblock %}#}

{% block page_title %}
    Document Request
{% endblock %}

{% block page_subtitle %}
    List of document request of residents
{% endblock %}

{% block content %}
    <div class="container mt-3 mb-8">
        <div class="col-md-12">
            <div class="page-people-directory">
                <div class="row">
                    <div class="col-md-12">
                        <div class="row">
                            <div class="col-md-6">
                                <h5 class="test-test-test">Pending Requests</h5>
                            </div>
                            <div class="col-md-6 d-flex justify-content-end h-50">
                                <a class="btn btn-secondary mx-2" href="{% url "appointment:my_document_request" %}">My
                                    request</a>
                                <a class="btn btn-primary mx-2" href="{% url "appointment:request_document" %}">Request
                                    Document</a>
                            </div>
                        </div>
                        <table id="example" class="table table-striped" style="width: 100%">
                            <thead>
                                <tr>
                                    <td></td>
                                </tr>
                            </thead>
                            <tbody>
                                {% for data in request_list %}
                                    <tr>
                                        <td>
                                            <div class="list-group-item">
                                                <div class="list-group contact-group">
                                                    <div class="media">
                                                        <div class="pull-left me-3">
                                                            <img class="rounded-circle"
                                                                src="{{ data.photo_url }}"
                                                                alt="user-profile">
                                                        </div>
                                                        <div class="media-body">
                                                            <div class="container m-0">
                                                                <div class="row">
                                                                    <div class="col-8">
                                                                        <h4 class="media-heading">{{ data.first_name }} {{ data.middle_name }} {{ data.last_name }}
                                                                            <small>{{ data.role|capfirst }}</small></h4></div>
                                                                    <div class="col-4">
                                                                        <p class="text-end">Request Status: {{ data.status }}</p>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                            <div class="media-content">
                                                                <div class="row py-1">
                                                                    <div class="col-6"><i
                                                                        class="fas fa-map-marker-alt me-2"></i> {{ data.address }}
                                                                    </div>
                                                                    <div class="col-6"><i
                                                                        class="fas fa-mobile me-2"></i> {{ data.contact_number }}
                                                                    </div>
                                                                </div>
                                                                <div class="row py-1">
                                                                    <div class="col-6"><i
                                                                        class="fas fa-envelope me-2"></i> {{ data.email }}</div>
                                                                    <div class="col-6"><i
                                                                        class="fas fa-file-alt me-2"></i> {{ data.document_list|join:"," }}
                                                                    </div>
                                                                </div>
                                                            </div>
                                                            <hr/>
                                                            <div class="container">
                                                                <div class="row">
                                                                    <div class="col-6">
                                                                        Requested on: {{ data.created_on }}
                                                                    </div>
                                                                    <div class="col-6 d-flex justify-content-end">
                                                                        <a class="btn btn-primary mx-2"
                                                                            href="{% url "appointment:user_document_verification" data.document_id %}">View</a>
                                                                        <button data-id="{{ data.document_id }}"
                                                                            class="btn btn-danger mx-2 btn-cancel"
                                                                            id="btn-cancel"
                                                                            formtarget="_parent"
                                                                            type="button">
                                                                            Cancel
                                                                        </button>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                {% endfor %}
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    </div>
    </div>
{% endblock %}

{% block scripts %}
    <script type="text/javascript">
        $(document).ready(function () {
            $('#example').DataTable({
                "paging": true,
                "ordering": false,
                "info": true
            });

            $(".btn-cancel").click(function () {
                Swal.fire({
                    title: 'Are you sure?',
                    text: "You want to cancel this request!",
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Yes, cancel it!'
                }).then((result) => {
                    if (result.isConfirmed) {
                        Swal.fire(
                            'Deleted!',
                            'The document request has been deleted.',
                            'success'
                        ).then((result) => {
                            let button_id = $(this).data("id")
                            let location_url = '{% url "appointment:document_cancel" %}';
                            window.location.href = location_url.concat(button_id)
                        })
                    }
                })
            });
        });
    </script>
{% endblock %}

appointment/templates/appointment/my_document_request.html
{% extends "layouts/base_table.html" %}

{% load static %}

{% block title %}
    Barangay Admin - My Document Request
{% endblock %}

{% block stylesheets %}
    {{ block.super }}

    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>

    <link href="{% static "appointment/assets/css/my_document_request.css" %}" rel="stylesheet">
{% endblock %}


{% block back_button %}
    {% if user_sess_data.role in 'admin, head_admin, secretary, worker ' %}
        <div class="mb-1">
            <a href="{% url "appointment:document_request" %}"><--Go back to document request</a>
        </div>
    {% else %}
        <a href="{% url "services:index" %}"><--Go back to services</a>
    {% endif %}
{% endblock %}

{% block page_title %}
    My Document Request
{% endblock %}

{% block page_subtitle %}
    List of your document request.
{% endblock %}

{% block content %}
    {% if user_sess_data.role not in 'admin, head_admin, secretary, worker ' %}
        <div class="col-md-6 d-flex justify-content-end h-50 w-100 pb-2">
            <a class="btn btn-primary mx-2" href="{% url "appointment:request_document" %}">+ Request
                Document</a>
        </div>
    {% endif %}
{% endblock %}

{% block table_content %}
    <thead class="table-dark">
        <tr>
            <th data-field="request_id" data-visible="false" data-sortable="true" class="border-0">REQUEST I.D</th>
            <th data-field="document" data-sortable="true">DOCUMENT</th>
            <th data-field="purpose" data-sortable="true">PURPOSE</th>
            <th data-field="status" data-sortable="true">STATUS</th>
            <th data-field="action" data-sortable="true">APPOINTMENT ACTION
                {#        <th data-field="action" data-formatter="operateFormatter" data-events="operateEvents" class="border-0">ACTION#}
            </th>
        </tr>
    </thead>
    <tbody>
        {% for data in request_data %}
            <tr>
                <td class="fw-bold d-flex align-items-center">{{ data.document_id }}</td>
                <td>{{ data.document|unordered_list }}</td>
                <td>{{ data.appointment_purpose }}</td>
                <td>{{ data.status }}</td>
                <td>
                    {% if data.status == "get" %}
                        {% if "start_appointment" in data %}
                            <div class="btn btn-success">
                                <i class="fas fa-check-circle"></i>
                            </div>
                        {% else %}
                            <a class="btn btn-primary" href="{% url "appointment:appointment_schedule" data.document_id %}">
                                <i class="fas fa-calendar-alt"></i></a>
                        {% endif %}
                    {% else %}
                        <a class="btn btn-light" href="#"><i class="fas fa-calendar-alt" style="color: lightgrey;"></i></a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    </tbody>
{% endblock table_content %}

{% block scripts %}

    {{ block.super }}

    <script type="text/javascript">
        $(document).ready(function () {
            {{ block.super }}
        });
    </script>

    {#    <script>#}
    {#        function operateFormatter(value, row, index) {#}
    {#            return [#}
    {#                '<a class="like" href="javascript:void(0)" title="Like">',#}
    {#                '<i class="fas fa-calendar-alt"></i>',#}
    {#                '</a>  ',#}
    {#            ].join('');#}
    {#        }#}
    {##}
    {#        window.operateEvents = {#}
    {#            'click .like': function (e, value, row, index) {#}
    {#                window.location.href = "{% url "appointment:schedule" document_id %}"#}
    {#alert(`You click like action, row: ${JSON.stringify(row)}`);#}
    {#            },#}
    {#        };#}
    {#    </script>#}


    {{ form.media.js }}
    <script type="text/javascript">
        $(document).ready(function () {
            $('#id_date').datetimepicker({
                format: 'F d, Y',
                minDate: 0,
                onGenerate: function (ct) {
                    $(this).find('.xdsoft_date.xdsoft_weekend')
                        .addClass('xdsoft_disabled');
                },
                minTime: '8:00',
                maxTime: '17:00',
                step: 15,
                allowTimes: {{ filtered_allowed_times|safe }}
            });
        });
    </script>

    <script>
        {% if messages %}
            {% for message in messages %}
                {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                    Swal.fire({
                        title: "Success",
                        icon: "success",
                        text: '{{ message }}',
                    })
                {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                    Swal.fire({
                        title: "Error!",
                        icon: "error",
                        text: "{{ message }}",
                    })
                {% endif %}
            {% endfor %}
        {% endif %}
    </script>
{% endblock %}

appointment/templates/appointment/request_document.html
{% extends "layouts/base.html" %}
{% load poll_extras %}

{% load static %}

{% block title %}
    Barangay Admin - Document Requests
{% endblock %}

{% block stylesheets %}
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>

    <link href="{% static "appointment/assets/css/request_document.css" %}" rel="stylesheet">
    {{ form.media.css }}
{% endblock %}

{% block back_button %}
    <div class="mb-1">
        {% if user_sess_data.role in 'admin, head_admin, secretary, worker ' %}
            <a href="{% url "appointment:document_request" %}"><--Go back to request</a>
        {% else %}
            <a href="{% url "appointment:my_document_request" %}"><--Go back to my document request</a>
        {% endif %}
    </div>
{% endblock %}

{% block page_title %}
    Document Request
{% endblock %}
Select your document.
{% block page_subtitle %}

{% endblock %}

{% block content %}

    {% load crispy_forms_tags %}

    <div class="container">
        <div class="row">
            <div class="col-12">
                <form action="{% url "appointment:request_document" %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}
                    {{ document_url }}
                    <div class="container">
                        <div class="row">
                            <div class="col-12 d-flex justify-content-center">
                                {% if user_sess_data.role in 'admin, head_admin, secretary, worker ' %}
                                    <a class="btn btn-secondary mx-2" href="{% url "services:index" %}">Cancel</a>
                                {% else %}
                                    {% if user_sess_data.role in 'admin, head_admin, secretary, worker ' %}
                                        <a class="btn btn-secondary mx-2"
                                            href="{% url "appointment:document_request" %}">Cancel</a>
                                    {% else %}
                                        <a class="btn btn-secondary mx-2"
                                            href="{% url "appointment:my_document_request" %}">Cancel</a>
                                    {% endif %}
                                {% endif %}
                                <button class="btn btn-primary mx-2 btn-submit" id="submit" type="submit">Submit
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>


{% endblock %}

{% block scripts %}
    {{ form.media.js }}
    <script type="text/javascript">
        $(document).ready(function () {
            $('#id_date').datetimepicker({
                format: 'F d, Y',
                minDate: 0,
                onGenerate: function (ct) {
                    $(this).find('.xdsoft_date.xdsoft_weekend')
                        .addClass('xdsoft_disabled');
                },
                minTime: '8:00',
                maxTime: '17:00',
                step: 15,
                allowTimes: {{ filtered_allowed_times|safe }}
            });
        });
    </script>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#submit").submit(function (e) {
                e.preventDefault()
                let form = $(this).parents('form');
                Swal.fire({
                    title: 'Are you sure?',
                    text: "You want submit your request!",
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Yes'
                }).then((result) => {
                    if (result.isConfirmed) {
                        Swal.fire(
                            'Success!',
                            'Your request has been sent to secretary',
                            'success'
                        ).then((result) => {
                            form.submit();
                        });
                    }
                })
            });
        });
    </script>
{% endblock %}