announcement/urls.py
"""Create your announcement url routing here."""
from django.urls import path

from . import views

app_name = "announcement"

urlpatterns = [
    path(
        "",
        views.AnnouncementHomeView.as_view(),
        name="home",
    ),
    path(
        "create/",
        views.AnnouncementCreateView.as_view(),
        name="create",
    ),
    path(
        "edit/<slug:announcement_id>/",
        views.AnnouncementEditView.as_view(),
        name="edit",
    ),
    path(
        "delete/<slug:announcement_id>/<str:thumbnail_name>",
        views.delete,
        name="delete",
    ),
    path(
        "view/<slug:announcement_id>/",
        views.AnnouncementDetailView.as_view(),
        name="view",
    ),
]

api/urls.py
"""URLConfig for api."""
from django.urls import path

from . import views

urlpatterns = [
    path("data_viz/", views.DataVizApiView.as_view()),
    path("ocr/<str:filename>", views.OcrApiView.as_view()),
    path("notification/", views.SendNotification.as_view()),
]

one_barangay/urls.py
from django.urls import include, path, re_path
from django.views.decorators.cache import cache_control
from django.views.generic import TemplateView

urlpatterns = [
    path("ocr/", include("ocr.urls")),
    path("", include("app.urls")),
    path("dashboard", include("data_viz.urls")),
    path("", include("authentication.urls")),
    path("user_management/", include("user_management.urls")),
    path("user_profile/", include("user_profile.urls")),
    path("announcement/", include("announcement.urls")),
    path("bulk-sched/", include("bulk_sched.urls")),
    path("complaint/", include("complaint.urls")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    re_path(
        r"^service-worker.js",
        cache_control(max_age=2592000)(
            TemplateView.as_view(
                template_name="service-worker.js",
                content_type="application/javascript",
            )
        ),
        name="service-worker.js",
    ),
    path("appointment/", include("appointment.urls")),
    re_path(
        r"^firebase-messaging-sw.js",
        cache_control(max_age=2592000)(
            TemplateView.as_view(
                template_name="firebase-messaging-sw.js",
                content_type="application/javascript",
            )
        ),
        name="firebase-messaging-sw.js",
    ),
    path("api/", include("api.urls")),
]

announcement/models.py
"""Create your announcement models here."""

announcement/forms.py
"""Create your announcement forms here."""
from datetime import datetime

import pytz
from django import forms
from django.core.exceptions import ValidationError
from django.utils.text import slugify

from one_barangay.validators import validate_image
from one_barangay.widgets import CkeditorWidget

FEATURED_CHOICES = (
    (True, "Featured"),
    (False, "Not Featured"),
)

CATEGORIES_OPTIONS = (
    ("covid-19", "COVID-19"),
    ("political", "Political"),
    ("environmental", "Environmental"),
)


class AnnouncementBaseForm(forms.Form):
    """Base form for announcement."""

    error_css_class = "is-invalid"
    required_css_class = "required"

    user_id = forms.CharField(
        label="User I.D.",
        label_suffix="",
        widget=forms.HiddenInput(
            attrs={
                "readonly": True,
                "class": "form-control text-black",
            }
        ),
    )
    author = forms.CharField(
        label="Author",
        label_suffix="",
        widget=forms.HiddenInput(
            attrs={
                "readonly": True,
                "class": "form-control text-black",
            }
        ),
    )
    photo_url = forms.URLField(
        label="Profile Picture",
        label_suffix="",
        widget=forms.HiddenInput(
            attrs={
                "readonly": True,
                "class": "form-control text-black",
            }
        ),
    )
    title = forms.CharField(
        label="Title",
        max_length=150,
        min_length=5,
        label_suffix="",
        widget=forms.TextInput(attrs={"class": "form-control text-black"}),
    )

    thumbnail = forms.ImageField(
        validators=[validate_image],
        widget=forms.ClearableFileInput(attrs={"class": "form-control"}),
    )

    body = forms.CharField(widget=CkeditorWidget)

    categories = forms.MultipleChoiceField(
        widget=forms.SelectMultiple(attrs={"class": "form-select"}), choices=CATEGORIES_OPTIONS
    )

    featured = forms.ChoiceField(
        label_suffix="",
        initial=False,
        widget=forms.RadioSelect(attrs={"class": "form-checkbox list-unstyled"}),
        choices=FEATURED_CHOICES,
    )


class AnnouncementCreateForm(AnnouncementBaseForm):
    """Create form for announcement."""

    creation_date = forms.DateTimeField(
        label_suffix="",
        widget=forms.HiddenInput(attrs={"readonly": True, "class": "form-control text-black"}),
    )

    def __init__(self, *args, request, **kwargs):
        """Initialize AnnouncementCreateForm attributes."""
        super().__init__(*args, **kwargs)

        user_session = request.session.get("user")
        if user_session is not None:
            name = user_session.get("display_name")

            self.fields["author"].initial = name if name else user_session.get("first_name")
            self.fields["user_id"].initial = user_session.get("user_id")
            self.fields["photo_url"].initial = user_session.get("photo_url")

        self.fields["creation_date"].initial = datetime.now(tz=pytz.timezone("Asia/Manila"))

    def clean(self):
        """Customize cleaning for form fields."""
        cleaned_data = super().clean()
        cleaned_data = {key: value for key, value in cleaned_data.items() if value}
        return cleaned_data

    def clean_date(self):
        """Clean date form field."""
        date = self.cleaned_data.get("date")

        if not date:
            date = datetime.now().strftime("%B %d, %Y %H:%M:%S")
        else:
            date = date.strftime("%B %d, %Y %H:%M:%S")

        return date

    def clean_title(self):
        """Clean title form field."""
        title = self.cleaned_data.get("title")

        if len(title) < 5:
            raise ValidationError("You need to have at least 5 characters for your title!")

        if not title:
            raise ValidationError("You need to supply a title for your announcement!")
        else:
            self.cleaned_data["announcement_id"] = slugify(title)

        return title

    def clean_thumbnail(self):
        """Clean thumbnail form field."""
        thumbnail = self.cleaned_data.get("thumbnail")

        if thumbnail is None:
            raise ValidationError("This field is required!")
        else:
            if not thumbnail.content_type.startswith("image"):
                raise ValidationError("File is not image.")

        return thumbnail


class AnnouncementEditForm(AnnouncementCreateForm):
    """Edit form for announcement."""

    updated = forms.DateTimeField(
        label="updated",
        label_suffix="",
        widget=forms.HiddenInput(attrs={"readonly": True, "class": "form-control text-black"}),
    )
    thumbnail_name = forms.CharField(widget=forms.HiddenInput())

    def __init__(self, *args, announcement, **kwargs):
        """Initialize AnnouncementEditForm attributes."""
        super().__init__(*args, **kwargs)

        self.fields["title"].initial = announcement["title"]
        self.fields["body"].initial = announcement["body"]
        self.fields["creation_date"].initial = announcement["creation_date"]
        self.fields["categories"].initial = announcement["categories"]
        self.fields["featured"].initial = announcement["featured"]
        self.fields["thumbnail_name"].initial = announcement["thumbnail_name"]
        self.fields["updated"].initial = datetime.now()

announcement/views.py
"""Create your announcement views here."""

from django.contrib import messages
from django.core.files.storage import default_storage
from django.http import HttpResponse, HttpResponseRedirect
from django.template.defaultfilters import safe, striptags, truncatewords
from django.urls import reverse_lazy
from django.views.generic import FormView, TemplateView
from firebase_admin import firestore

from announcement.forms import AnnouncementCreateForm, AnnouncementEditForm
from one_barangay.mixins import ContextPageMixin, FormInvalidMixin
from one_barangay.notification import Notification
from one_barangay.settings import firebase_app


class AnnouncementHomeView(ContextPageMixin, TemplateView):
    """Template view for announcement home."""

    template_name = "announcement/home.html"
    segment = "announcement"
    title = "Announcement"
    sub_title = "View announcements / events created in oneBarangay."

    def get(self, request, *args, **kwargs) -> HttpResponse:
        """Get all announcement from firestore.

        Args:
          request: The URL request.
          *args: Additional arguments.
          **kwargs: Additional keyword arguments.

        Returns:
          Render HttpResponse to announcement/home.html along with context data.
        """
        context = self.get_context_data(**kwargs)
        db = firestore.client(app=firebase_app)

        featured_docs = (
            db.collection("announcements")
            .where("featured", "==", True)
            .order_by("creation_date", direction="DESCENDING")
            .stream()
        )
        featured_announcements = [doc.to_dict() for doc in featured_docs]

        not_featured_docs = (
            db.collection("announcements")
            .where("featured", "==", False)
            .order_by("creation_date", direction="DESCENDING")
            .stream()
        )
        not_featured_announcements = [doc.to_dict() for doc in not_featured_docs]
        new_announcements = []
        old_announcements = []
        for post in not_featured_announcements:
            if (post["creation_date"].hour - 168) >= 0:
                old_announcements.append(post)
            else:
                new_announcements.append(post)

        context["featured_announcements"] = featured_announcements
        context["new_announcements"] = new_announcements
        context["old_announcements"] = old_announcements

        return self.render_to_response(context)


class AnnouncementCreateView(FormView):
    """Form view for creating announcement."""

    form_class = AnnouncementCreateForm
    template_name = "announcement/create.html"
    success_url = reverse_lazy("announcement:create")

    def get_form_kwargs(self):
        """Pass request session to form."""
        kwargs = super().get_form_kwargs()
        kwargs["request"] = self.request
        return kwargs

    def form_valid(self, form):
        """Call when AnnouncementCreateForm is VALID.

        Args:
          form: The submitted AnnouncementCreateForm.

        Returns:
          The valid AnnouncementCreateForm submitted.
        """
        db = firestore.client(app=firebase_app)
        form.cleaned_data["featured"] = form.cleaned_data["featured"] == "True"

        # Upload Thumbnail
        thumbnail_name = default_storage.get_valid_name(form.cleaned_data["thumbnail"].name)
        default_storage.save(thumbnail_name, form.cleaned_data["thumbnail"])

        form.cleaned_data["thumbnail_name"] = thumbnail_name
        form.cleaned_data["thumbnail"] = default_storage.url(thumbnail_name)

        db.collection("announcements").document(form.cleaned_data["announcement_id"]).set(form.cleaned_data, merge=True)
        # TODO: Go back to home after finished creating
        messages.success(self.request, "Post has been saved!")
        notification = Notification()
        notification.send_notification(
            form.cleaned_data["title"],
            safe(striptags(truncatewords(form.cleaned_data["body"], 25))),
        )

        return super().form_valid(form)

    def form_invalid(self, form):
        """Call when AnnouncementCreateForm is INVALID.

        Args:
          form: The submitted AnnouncementCreateForm.

        Returns:
          The invalid AnnouncementCreateForm submitted.
        """
        messages.error(self.request, "Post has not been saved!")

        return super().form_invalid(form)

    def get_context_data(self, **kwargs) -> dict:
        """Get context data to announcement create view.

        Args:
          **kwargs: Keyword arguments.

        Returns:
          The dictionary data needed by announcement create view.
        """
        context = super().get_context_data()
        context["segment"] = "announcement"
        context["title"] = "Add Announcement"
        context["sub_title"] = "Create announcement / events that everyone can see."
        context["hidden_fields"] = ["created", "author", "uid", "photo_url"]

        return context


# TODO: Go back to home after finished editing
#  TODO: Add buttons to prompt the user to go back
class AnnouncementEditView(FormInvalidMixin, FormView):
    """Form view for creating announcement."""

    form_class = AnnouncementEditForm
    template_name = "announcement/create.html"
    success_url = reverse_lazy("announcement:create")
    error_message = "Post has not been edited! Please fix the errors in the form."

    def __init__(self):
        """Initialize AnnouncementEditView attributes."""
        self.db = firestore.client(app=firebase_app)
        self.announcement_ref = self.db.collection("announcements")

    def get_form_kwargs(self):
        """Pass announcement_id and request session to AnnouncementEditForm."""
        kwargs = super().get_form_kwargs()
        announcement_id = self.kwargs["announcement_id"]
        kwargs["request"] = self.request

        announcement = self.announcement_ref.document(announcement_id).get().to_dict()
        kwargs["announcement"] = announcement

        return kwargs

    def form_valid(self, form):
        """Call when AnnouncementEditForm is VALID.

        Args:
          form: The submitted AnnouncementEditForm.

        Returns:
          The valid form submitted.
        """
        changed_fields = {}
        announcement_id = self.kwargs["announcement_id"]
        if form.has_changed():
            # Accumulate all data of changed fields.
            for field in form.changed_data:
                # Delete the previous thumbnail
                if field == "thumbnail":
                    # Delete Previous Thumbnail
                    default_storage.delete(form.cleaned_data["thumbnail_name"])

                    # Upload Thumbnail
                    thumbnail_name = default_storage.generate_filename(form.cleaned_data["thumbnail"].name)
                    default_storage.save(thumbnail_name, form.cleaned_data["thumbnail"])

                    form.cleaned_data["thumbnail_name"] = thumbnail_name
                    changed_fields["thumbnail_name"] = form.cleaned_data["thumbnail_name"]

                    form.cleaned_data["thumbnail"] = default_storage.url(thumbnail_name)
                if field == "featured":
                    form.cleaned_data[field] = form.cleaned_data[field] == "True"

                changed_fields[field] = form.cleaned_data[field]

            self.announcement_ref.document(announcement_id).update(changed_fields)

        messages.success(self.request, "Post has been edited!")

        return super().form_valid(form)

    def get_context_data(self, **kwargs) -> dict:
        """Get context data to announcement edit view.

        Args:
          **kwargs: Additional keyword arguments.

        Returns:
          The dictionary data needed by announcement edit view.
        """
        context = super().get_context_data()
        context["segment"] = "announcement"
        context["title"] = "Edit Announcement"
        context["sub_title"] = "Modify your existing announcement."
        context["hidden_fields"] = ["created", "author", "uid", "photo_url", "updated"]

        return context


# TODO: Notify for success or fail of deleting
# TODO: Display warning for deleting
def delete(request, announcement_id, thumbnail_name, *args, **kwargs) -> HttpResponseRedirect:
    """Delete announcement.

    Args:
      request: The URL request.
      announcement_id: The unique id of the announcement.
      thumbnail_name: The name of the thumbnail to delete.
      *args: Additional arguments.
      **kwargs: Additional Keyword arguments.

    Returns:
      HttpResponseRedirect to announcement home.
    """
    db = firestore.client(app=firebase_app)
    default_storage.delete(thumbnail_name)
    db.collection("announcements").document(announcement_id).delete()

    messages.success(request, "successfully deleted post!")

    return HttpResponseRedirect(reverse_lazy("announcement:home"))


class AnnouncementDetailView(ContextPageMixin, TemplateView):
    """Class for viewing a single announcement."""

    template_name = "announcement/view.html"
    title = "View Announcement"
    sub_title = "View each the announcement in oneBarangay in detail."
    segment = "announcement"

    def get(self, request, *args, **kwargs) -> HttpResponse:
        """Get a single announcement from firestore.

        Args:
          request: The URL request.
          *args: Additional arguments.
          **kwargs: Additional keyword arguments.

        Returns:
          HttpResponse to announcement/view.html with context data.
        """
        context = self.get_context_data(**kwargs)
        db = firestore.client(app=firebase_app)

        post = db.collection("announcements").document(self.kwargs["announcement_id"]).get().to_dict()
        context["post"] = post

        return self.render_to_response(context)

announcement/templates/announcement/home.html
{% extends "layouts/base.html" %}
{% block title %}{{ title }}{% endblock %}
{% load static %}

{% block stylesheets %}
    <link rel="stylesheet" href="{% static "/announcement/assets/css/styles.css" %}">
{% endblock %}

<!-- Page Title & Subtitle -->
{% block page_title %}{{ title }}{% endblock page_title %}
{% block page_subtitle %}{{ sub_title }}{% endblock page_subtitle %}

{% block content %}
    <div class="pb-4">
        <a href="{% url "announcement:create" %}" class="btn btn-secondary">
            <svg class="icon icon-xs" fill="none"
                stroke="currentColor" viewBox="0 0 24 24"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path d="M12 6v6m0 0v6m0-6h6m-6 0H6"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                >
                </path>
            </svg>
            Add
        </a>
    </div>

    <article>
        <div class="hr-theme-slash-2 mb-4 align-middle">
            <div class="hr-line border-5"></div>
            <div class="hr-icon fs-1 fw-bold text-nowrap">FEATURED 📌</div>
            <div class="hr-line border-5"></div>
        </div>

        <div class="row row-cols-1 row-cols-sm-4 g-4 position-relative justify-content-center">
            {% for post in featured_announcements %}
                <div id="{{ post.announcement_id }}" class="col">
                    <div class="card text-center">
                        <h2 class="card-header badge bg-primary text-wrap p-2">Featured</h2>
                        <!-- Post thumbnail -->
                        <figure>
                            <div class="thumbnail">
                                {% if post.thumbnail %}
                                    <img class="m-0" src="{{ post.thumbnail }}" alt="post-thumbnail">
                                {% else %}
                                    <img class="m-0" src="{% static "/assets/img/default-blog-image.jpg" %}" alt="default-thumbnail">
                                {% endif %}
                            </div>
                        </figure>
                        <div class="card-body">
                            <!-- Post title -->
                            <h5 class="card-title">{{ post.title|title }}</h5>
                            <!-- Post categories -->
                            <div class="mb-3">
                                {% for category in post.categories %}
                                    <a class="badge bg-secondary text-decoration-none link-light"
                                        href="#">{{ category|title }}</a>
                                {% endfor %}
                            </div>
                            <!-- Post content -->
                            <section>{{ post.body|safe|striptags|lower|truncatewords:25 }}</section>
                            <!-- Post actions -->
                            <div class="buttons text-end pt-4">
                                {% if request.session.user.role != "resident" and request.session.user.role != "secretary" %}
                                    <a href="{% url "announcement:delete" post.announcement_id post.thumbnail_name %}"
                                        class="btn btn-danger">Delete</a>
                                    <a href="{% url "announcement:edit" post.announcement_id %}"
                                        class="btn btn-primary">Edit</a>
                                {% endif %}
                                <a href="{% url "announcement:view" post.announcement_id %}"
                                    class="btn btn-info">View</a>
                            </div>
                        </div>
                        <!-- Post meta content-->
                        <div class="card-footer text-muted">
                            {% if post.updated %}
                                Updated {{ post.updated|timesince }} ago
                            {% else %}
                                Created {{ post.creation_date|timesince }} ago
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% empty %}
                <div class="text-center fs-1">Sorry, no featured post this time.</div>
            {% endfor %}
        </div>
    </article>

    <article>
        <div class="hr-theme-slash-2 mb-4">
            <div class="hr-line border-5"></div>
            <div class="hr-icon fs-1 fw-bold text-nowrap">NEW 🌟</div>
            <div class="hr-line border-5"></div>
        </div>

        <div class="row row-cols-1 row-cols-sm-4 g-4 position-relative justify-content-center">
            {% for post in new_announcements %}
                <div id="{{ post.announcement_id }}" class="col">
                    <div class="card text-center">
                        <h2 class="card-header badge bg-primary text-wrap p-2">New</h2>
                        <!-- Post thumbnail -->
                        <figure>
                            <div class="thumbnail">
                                {% if post.thumbnail %}
                                    <img class="m-0" src="{{ post.thumbnail }}" alt="post-thumbnail">
                                {% else %}
                                    <img class="m-0" src="{% static "/assets/img/default-blog-image.jpg" %}" alt="default-thumbnail">
                                {% endif %}
                            </div>
                        </figure>
                        <div class="card-body">
                            <!-- Post title -->
                            <h5 class="card-title">{{ post.title|title }}</h5>
                            <!-- Post categories -->
                            <div class="mb-3">
                                {% for category in post.categories %}
                                    <a class="badge bg-secondary text-decoration-none link-light"
                                        href="#">{{ category|title }}</a>
                                {% endfor %}
                            </div>
                            <!-- Post content -->
                            <section>{{ post.body|safe|striptags|lower|truncatewords:25 }}</section>
                            <!-- Post actions -->
                            <div class="buttons text-end pt-4">
                                {% if request.session.user.role != "resident" and request.session.user.role != "secretary" %}
                                    <a href="{% url "announcement:delete" post.announcement_id post.thumbnail_name %}"
                                        class="btn btn-danger">Delete</a>
                                    <a href="{% url "announcement:edit" post.announcement_id %}"
                                        class="btn btn-primary">Edit</a>
                                {% endif %}
                                <a href="{% url "announcement:view" post.announcement_id %}"
                                    class="btn btn-info">View</a>
                            </div>
                        </div>
                        <!-- Post meta content-->
                        <div class="card-footer text-muted">
                            {% if post.updated %}
                                Updated {{ post.updated|timesince }} ago
                            {% else %}
                                Created {{ post.creation_date|timesince }} ago
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% empty %}
                <div class="text-center fs-1">Sorry, no new post this time.</div>
            {% endfor %}
        </div>
    </article>

    <article>
        <div class="hr-theme-slash-2 mb-4 align-middle">
            <div class="hr-line border-5"></div>
            <div class="hr-icon fs-1 fw-bold text-nowrap">OLD 🐢</div>
            <div class="hr-line border-5"></div>
        </div>
        <div class="row row-cols-1 row-cols-sm-4 g-4 position-relative justify-content-center">
            {% for post in old_announcements %}
                <div id="{{ post.announcement_id }}" class="col">
                    <div class="card text-center">
                        <h2 class="card-header badge bg-primary text-wrap p-2">Old</h2>
                        <!-- Post thumbnail -->
                        <figure>
                            <div class="thumbnail">
                                {% if post.thumbnail %}
                                    <img class="m-0" src="{{ post.thumbnail }}" alt="post-thumbnail">
                                {% else %}
                                    <img class="m-0" src="{% static "/assets/img/default-blog-image.jpg" %}" alt="default-thumbnail">
                                {% endif %}
                            </div>
                        </figure>
                        <div class="card-body">
                            <!-- Post title -->
                            <h5 class="card-title">{{ post.title|title }}</h5>
                            <!-- Post categories -->
                            <div class="mb-3">
                                {% for category in post.categories %}
                                    <a class="badge bg-secondary text-decoration-none link-light"
                                        href="#">{{ category|title }}</a>
                                {% endfor %}
                            </div>
                            <!-- Post content -->
                            <section>{{ post.body|safe|striptags|lower|truncatewords:25 }}</section>
                            <!-- Post actions -->
                            <div class="buttons text-end pt-4">
                                {% if request.session.user.role != "resident" and request.session.user.role != "secretary" %}
                                    <a href="{% url "announcement:delete" post.announcement_id post.thumbnail_name %}"
                                        class="btn btn-danger">Delete</a>
                                    <a href="{% url "announcement:edit" post.announcement_id %}"
                                        class="btn btn-primary">Edit</a>
                                {% endif %}
                                <a href="{% url "announcement:view" post.announcement_id %}"
                                    class="btn btn-info">View</a>
                            </div>
                        </div>
                        <!-- Post meta content-->
                        <div class="card-footer text-muted">
                            {% if post.updated %}
                                Updated {{ post.updated|timesince }} ago
                            {% else %}
                                Created {{ post.creation_date|timesince }} ago
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% empty %}
                <div class="text-center fs-1">Sorry, no old post this time.</div>
            {% endfor %}
        </div>
    </article>
{% endblock content %}

{% block scripts %}
    <script>
        const swalWithBootstrapButtons = Swal.mixin({
            customClass: {
                confirmButton: 'btn btn-success',
                cancelButton: 'btn btn-danger me-2'
            },
            buttonsStyling: false
        })
        {% if messages %}
            {% for message in messages %}
                {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                    swalWithBootstrapButtons.fire({
                        title: "Success",
                        icon: "success",
                        text: '{{ message }}',
                        confirmButtonText: 'Yes!',
                        cancelButtonText: 'No.'
                    }).then((result) => {
                        if (result.isConfirmed) {
                            window.location.href = "{% url "announcement:home" %}"
                        }
                    });
                {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                    swalWithBootstrapButtons.fire({
                        title: "Error!",
                        icon: "error",
                        text: "{{ message }}",
                        confirmButtonText: 'OK'
                    })
                {% endif %}
            {% endfor %}
        {% endif %}
    </script>
{% endblock scripts %}