api/urls.py
"""URLConfig for api."""
from django.urls import path

from . import views

urlpatterns = [
    path("data_viz/", views.DataVizApiView.as_view()),
    path("ocr/<str:filename>", views.OcrApiView.as_view()),
    path("notification/", views.SendNotification.as_view()),
]

ocr/urls.py
"""URL Routing for OCR."""
from django.urls import path

from . import views

app_name = "ocr"

urlpatterns = [
    # OCR Table Section
    path(
        "",
        views.OcrHomeView.as_view(),
        name="home",
    ),
    path(
        "edit/<str:house_num>",
        views.OcrEditView.as_view(),
        name="edit",
    ),
    path(
        "delete/<str:house_num>",
        views.delete,
        name="delete",
    ),
    path(
        "detail/<str:house_num>",
        views.OcrDetailView.as_view(),
        name="detail",
    ),
    # OCR Scan Section
    path(
        "upload",
        views.OcrFileUploadView.as_view(),
        name="upload",
    ),
    path(
        "remove/<str:filename>",
        views.remove_file,
        name="remove_file",
    ),
    path(
        "scan_result/<str:filename>",
        views.OcrResultView.as_view(),
        name="scan_result",
    ),
]

one_barangay/urls.py
from django.urls import include, path, re_path
from django.views.decorators.cache import cache_control
from django.views.generic import TemplateView

urlpatterns = [
    path("ocr/", include("ocr.urls")),
    path("", include("app.urls")),
    path("dashboard", include("data_viz.urls")),
    path("", include("authentication.urls")),
    path("user_management/", include("user_management.urls")),
    path("user_profile/", include("user_profile.urls")),
    path("announcement/", include("announcement.urls")),
    path("bulk-sched/", include("bulk_sched.urls")),
    path("complaint/", include("complaint.urls")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    re_path(
        r"^service-worker.js",
        cache_control(max_age=2592000)(
            TemplateView.as_view(
                template_name="service-worker.js",
                content_type="application/javascript",
            )
        ),
        name="service-worker.js",
    ),
    path("appointment/", include("appointment.urls")),
    re_path(
        r"^firebase-messaging-sw.js",
        cache_control(max_age=2592000)(
            TemplateView.as_view(
                template_name="firebase-messaging-sw.js",
                content_type="application/javascript",
            )
        ),
        name="firebase-messaging-sw.js",
    ),
    path("api/", include("api.urls")),
]

ocr/views.py
"""Routing Request to Views of OCR Pages."""
import asyncio
import copy
import os
import random
import re
from datetime import date, datetime, timedelta
from typing import Union
from urllib.parse import urlparse

from dateutil import parser
from dateutil.parser import ParserError
from django.contrib import messages
from django.core.cache import cache
from django.core.files.storage import default_storage
from django.forms import formset_factory
from django.http import (
    HttpResponse,
    HttpResponsePermanentRedirect,
    HttpResponseRedirect,
    JsonResponse,
)
from django.shortcuts import redirect
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.datastructures import MultiValueDict
from django.views.generic import FormView, TemplateView
from firebase_admin import firestore
from google.api_core.exceptions import NotFound

from ocr.form_recognizer import form_recognizer_runner
from ocr.forms import OcrEditForm, OcrFamilyForm, OcrHouseForm, OcrUploadForm
from one_barangay.local_settings import logger
from one_barangay.mixins import ContextPageMixin, FormInvalidMixin
from one_barangay.settings import firebase_app, firestore_db
from one_barangay.templatetags.custom_template_tags import get_formset_field_name


class OcrFileUploadView(ContextPageMixin, FormView):
    """View for file upload."""

    form_class = OcrUploadForm
    template_name = "ocr/file_upload.html"
    success_url = reverse_lazy("ocr:upload")
    title = "File Upload"
    sub_title = "Upload RBI documents for scanning."
    segment = "ocr"

    def get_form_kwargs(self):
        """Return the keyword arguments for instantiating the form."""
        kwargs = super().get_form_kwargs()
        files = [self.request.FILES[file] for file in self.request.FILES]
        kwargs.update({"files": MultiValueDict({"file_upload": files})})

        return kwargs

    def post(self, request, *args, **kwargs):
        """POST request to upload OCR form files.

        Args:
          request: The URL request.
          **args: Additional arguments.
          **kwargs: Additional keyword arguments.

        Returns:
          A JSONResponse for success and failure of upload.
        """
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        files = [request.FILES[file] for file in request.FILES]

        file_data = []
        if form.is_valid():
            for file in files:
                filename = default_storage.generate_filename(file.name)
                default_storage.save(filename, file)
                thumbnail_url = default_storage.url(filename)

                path = urlparse(thumbnail_url).path
                ext = os.path.splitext(path)[1]
                if ext == ".pdf":
                    thumbnail_url = static("/assets/img/default-pdf-image.jpg")

                file_data.append((filename, thumbnail_url))

            if request.session.get("files"):
                request.session["files"] += file_data
            else:
                request.session["files"] = file_data

            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_invalid(self, form):
        """Call when OcrUploadForm is INVALID.

        Args:
          form: The submitted OcrUploadForm.

        Returns:
          The invalid OcrUploadForm submitted.
        """
        for field in form.errors:
            form[field].field.widget.attrs["class"] += " is-invalid"

        messages.error(self.request, "Files not uploaded!")
        return JsonResponse({"error": form.errors.as_json()}, status=400)


def remove_file(request, filename):
    """Remove a OCR uploaded file.

    Args:
      request: The URL request.
      filename: The name of the file to be remove.

    Returns:
      A HTTPResponseRedirect to OCR upload page.
    """
    remove(request.session, filename)

    return redirect("ocr:upload")


# TODO: Change color of feedback depending on confidence level.
class OcrResultView(ContextPageMixin, FormView):
    """View for scan result of ocr."""

    template_name = "ocr/scan_result.html"
    form_class = OcrFamilyForm
    success_url = reverse_lazy("ocr:upload")
    title = "OCR Result"
    sub_title = "Page for ocr result."
    segment = "ocr"
    error_message = "You got it wrong!"

    def get_context_data(self, **kwargs):
        """Insert the form into the context dict."""
        context = super().get_context_data(**kwargs)

        # For displaying RBI in HTML.
        context["document_type"] = os.path.splitext(kwargs["filename"])[1]
        context["document_url"] = default_storage.url(kwargs["filename"])
        context["document_name"] = kwargs["filename"]
        context["client_id"] = os.getenv("ADOBE_CLIENT_ID")

        context["first_row"] = ["last_name", "first_name", "middle_name", "ext"]
        context["second_row"] = ["place_of_birth", "date_of_birth", "sex", "civil_status"]
        context["third_row"] = ["citizenship", "monthly_income", "remarks"]
        context["house_data_field"] = ["house_num", "address", "date_accomplished"]

        return context

    def get(self, request, *args, **kwargs) -> HttpResponse:  # noqa: C901
        """GET request to display OCR scan result.

        Args:
          request: The URL request.
          **args: Additional arguments.
          **kwargs: Additional keyword arguments.

        Returns:
          The context data with OCR result.
        """
        context = self.get_context_data(**kwargs)

        # if os.getenv("GAE_ENV", "").startswith("standard"):
        #     ocr_result = asyncio.run(form_recognizer_runner(kwargs["filename"]))
        # else:

        # Cache all requests.
        ocr_result = cache.get("ocr")
        if ocr_result is None:
            ocr_result = asyncio.run(form_recognizer_runner(kwargs["filename"]))
            cache.set("ocr", ocr_result, timeout=None)
            logger.warning("OCR result has been cached!")
        else:
            logger.info("OCR result is cached!")

        family_initial = []
        family_confidence = []
        house_initial = {}
        house_confidence = {}

        for family_data in ocr_result[1]:
            monthly_income = family_data["monthly_income"]["text"]
            date_of_birth = re.sub(r"\s", "", family_data["date_of_birth"]["text"])

            sex = family_data.get("sex_m_or_f", {"text": "M"}).get("text")
            if sex:
                sex = sex.capitalize()
                if sex in ["M", "Male"]:
                    sex = "Male"
                elif sex in ["F", "Female"]:
                    sex = "Female"
            else:
                sex = "Others"

            family_initial.append(
                {
                    "last_name": family_data["last_name_apelyido"]["text"],
                    "first_name": family_data["first_name_pangalan"]["text"],
                    "middle_name": family_data["middle_name"]["text"],
                    "ext": family_data["ext"]["text"],
                    "date_of_birth": parser.parse(date_of_birth).strftime("%B %d, %Y"),
                    "place_of_birth": family_data["place_of_birth"]["text"],
                    "sex": sex,
                    "civil_status": family_data["civil_status"]["text"],
                    "citizenship": family_data["citizenship"]["text"],
                    "monthly_income": int(re.sub(r"\D", "", monthly_income)),
                    "remarks": family_data["remarks"]["text"],
                }
            )
            family_confidence.append(
                {
                    "last_name": family_data["last_name_apelyido"]["confidence"],
                    "first_name": family_data["first_name_pangalan"]["confidence"],
                    "middle_name": family_data["middle_name"]["confidence"],
                    "ext": family_data["ext"]["confidence"],
                    "place_of_birth": family_data["place_of_birth"]["confidence"],
                    "date_of_birth": family_data["date_of_birth"]["confidence"],
                    "sex": family_data["sex_m_or_f"]["confidence"],
                    "civil_status": family_data["civil_status"]["confidence"],
                    "citizenship": family_data["citizenship"]["confidence"],
                    "monthly_income": family_data["monthly_income"]["confidence"],
                    "remarks": family_data["remarks"]["confidence"],
                }
            )
        house_initial["address"] = ocr_result[0]["address"]["text"]
        house_initial["date_accomplished"] = ocr_result[0]["date"]["text"]
        house_initial["house_num"] = ocr_result[0]["household_no."]["text"]

        house_confidence["address"] = ocr_result[0]["address"]["confidence"]
        house_confidence["date_accomplished"] = ocr_result[0]["date"]["confidence"]
        house_confidence["house_num"] = ocr_result[0]["household_no."]["confidence"]

        formset = formset_factory(OcrFamilyForm, extra=0)
        family_form = formset(initial=family_initial)

        house_form = OcrHouseForm(initial=house_initial)

        for field in house_form:
            field_name = field.html_name
            if field_name in ["address", "date_accomplished", "house_num"]:
                field_confidence = (
                    round(float(house_confidence.get(field_name)) * 100, 2) if house_confidence.get(field_name) else 0.0
                )
                if field_confidence <= 66.0:
                    field.field.widget.attrs["class"] += " is-invalid text-danger"
                else:
                    field.field.widget.attrs["class"] += " is-valid text-success"

                field.help_text = str(field_confidence)

        for form, confidence in zip(family_form, family_confidence):
            for field in form:
                field_name = get_formset_field_name(field.html_name)
                field_confidence = (

ocr/templates/ocr/detail.html
{% extends "layouts/base.html" %}
{% block title %}{{ title }}{% endblock %}
{% load static %}

<!-- Page Title & Subtitle -->
{% block page_title %}{{ title }}{% endblock page_title %}
{% block page_subtitle %}{{ sub_title }}{% endblock page_subtitle %}

{% block content %}
    <div class="py-4">
        <div class="row mb-4 d-flex justify-content-center">
            <div class="col-12 mb-4">
                <div class="card bg-yellow-100 border-0 shadow">
                    <canvas width="400" height="100"></canvas>
                </div>
            </div>
            {% for member in family %}
                <div class="col-12 col-sm-6 col-xl-3 mb-4">
                    <div class="card" style="border-radius: 15px;">
                        <div class="card-header text-center">
                            {{ member.remarks }}
                        </div>
                        <div class="card-body text-center">
                            <div class="mt-3 mb-4">
                                <img
                                    src="{% if member.photo_url %} {{ member.photo_url }} {% else %} {% static "/assets/img/icons/default_user.svg" %} {% endif %}"
                                    class="rounded-circle img-fluid" style="width: 100px;"
                                    alt="Profile Picture"/>
                            </div>
                            <h4 class="mb-2">{{ member.first_name }} {{ member.middle_name }} {{ member.last_name }}</h4>
                            <p class="text-muted mb-4">User Role <span class="mx-2">|</span> <a href="#!">Barangay {{ member.role|capfirst|default:"Resident" }}</a></p>
                            <div class="mb-4 pb-2">
                                <button type="button" class="btn btn-outline-primary btn-floating">
                                    <i class="fab fa-facebook-f fa-lg"></i>
                                    View
                                </button>
                                <button type="button" class="btn btn-outline-primary btn-floating">
                                    <i class="fab fa-twitter fa-lg"></i>
                                    Edit
                                </button>
                            </div>
                            <div class="d-flex justify-content-between text-center mt-3">
                                <div class="px-3 col">
                                    <p class="mb-2 h5">{{ member.contact_number }}</p>
                                    <p class="text-muted mb-0">Phone Number</p>
                                </div>
                            </div>
                            <div class="d-flex justify-content-center text-center mt-3">
                                <div class="row">
                                    <div class="col">
                                        <p class="mb-2 h5">{{ member.civil_status }}</p>
                                        <p class="text-muted mb-0">Civil Status</p>
                                    </div>
                                    <div class="col">
                                        <p class="mb-2 h5">{{ member.monthly_income }}</p>
                                        <p class="text-muted mb-0">Monthly Income</p>
                                    </div>
                                </div>
                            </div>
                            <div class="d-flex justify-content-center text-center mt-3">
                                <div class="row">
                                    <div class="col">
                                        <p class="mb-2 h5">{{ member.sex|default:"None Provided" }}</p>
                                        <p class="text-muted mb-0">Gender</p>
                                    </div>
                                    <div class="px-3 col">
                                        <p class="mb-2 h5">{{ member.age }}</p>
                                        <p class="text-muted mb-0">Age</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

ocr/templates/ocr/edit.html
{% extends "layouts/base.html" %}
{% block title %}{{ title }}{% endblock %}
{% load static %}

<!-- Page Title & Subtitle -->
{% block page_title %}{{ title }}{% endblock page_title %}
{% block page_subtitle %}{{ sub_title }}{% endblock page_subtitle %}

{% block content %}
    <div class="container-fluid py-4 w-25">
        <div class="card border-0 shadow components-section">
            <div class="card-body">
                <form enctype="multipart/form-data" method="post" id="ocr-edit-form">
                    {% csrf_token %}
                    {% if form.non_field_errors %}
                        <div class="alert alert-danger" role="alert">
                            {% for error in form.non_field_errors %}
                                <p class="text-center">{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                    {{ form.house_num }}

                    <div class="row">
                        <div class="form-group col text-black">
                            <!-- Form -->
                            <div class="form-group mb-4 col">
                                {{ form.address.label_tag }}
                                <div class="input-group">
                                    <span class="input-group-text" id="basic-addon2">
                                        <span class="fas fa-unlock-alt"></span>
                                    </span>
                                    {{ form.address }}


                                </div>
                                <div class="badge m-0 bg-danger text-uppercase">{{ form.address.errors|striptags }}</div>
                            </div>
                            <!-- End of Form -->

                            <!-- Form -->
                            <div class="form-group mb-4 col">
                                {{ form.street.label_tag }}
                                <div class="input-group">
                                    <span class="input-group-text" id="basic-addon2">
                                        <span class="fas fa-unlock-alt"></span>
                                    </span>
                                    {{ form.street }}
                                </div>
                                <div class="badge m-0 bg-danger text-uppercase">{{ form.street.errors|striptags }}</div>
                            </div>
                            <!-- End of Form -->
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <a
                    class="btn btn-link text-gray-600 ms-auto"
                    type="reset"
                    href="{% url  "ocr:home" %}"
                >
                    Cancel
                </a>
                <button
                    class="btn btn-secondary"
                    form="ocr-edit-form"
                    name="Submit Edit Changes"
                    type="submit"
                >
                    Save
                </button>
            </div>
        </div>
    </div>
{% endblock content %}

ocr/templates/ocr/file_upload.html
{% extends "layouts/base.html" %}
{% block title %}{{ title }}{% endblock %}
{% load static %}

{% block stylesheets %}
    {{ form.media.css }}
{% endblock %}

<!-- Page Title & Subtitle -->
{% block page_title %}{{ title }}{% endblock page_title %}
{% block page_subtitle %}{{ sub_title }}{% endblock page_subtitle %}

{% block content %}
    <div class="container">
        <form action="{% url "ocr:upload" %}" method="post" class="dropzone dz" id="ocr-file-upload" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="fallback">
                {{ form }}
            </div>
        </form>
        <!-- Buttons -->
        <div class="d-flex justify-content-center">
            <button class="btn btn-primary my-4" form="ocr-file-upload" id="submit" hidden type="submit">
                Upload
            </button>
        </div>
        <!-- End of Buttons -->

        <div id="preview" class="py-5" data-url="{% static "/assets/img/default-pdf-image.png" %}">
            {% if request.session.files %}
                <div class="row g-4">
                    {% for filename, img_url in request.session.files %}
                        <div class="col-3 col-md-3 col-sm-4">
                            <div class="card shadow text-center p-2">
                                <img src="{{ img_url }}" class="card-img-top img-thumbnail" alt="Uploaded File"/>
                                <div class="card-body">
                                    <h6 class="card-title">{{ filename }}</h6>
                                </div>
                                <div class="btn-group">
                                    <a type="button" class="btn mt-auto btn-outline-danger"
                                        href="{% url "ocr:remove_file" filename %}">
                                        Remove
                                    </a>
                                    <a type="button" class="btn mt-auto btn-outline-tertiary"
                                        href="{% url "ocr:scan_result" filename %}">
                                        <span class="fas fa-remove"></span>
                                        Scan
                                    </a>
                                </div>
                            </div>
                        </div>

                    {% endfor %}
                </div>
            {% endif %}
        </div>
    </div>

{% endblock %}
{% block scripts %}
    {{ form.media.js }}
{% endblock %}

ocr/templates/ocr/home.html
{% extends "layouts/base_table.html" %}
{% block title %}{{ title }}{% endblock %}
{% load static %}

<!-- Page Title & Subtitle -->
{% block page_title %}{{ title }}{% endblock page_title %}
{% block page_subtitle %}{{ sub_title }}{% endblock page_subtitle %}
<!-- TODO: Remove extra characters in checkbox -->
{% block content %}
    <div class="buttons pb-4">
        <a href="{% url "ocr:upload" %}">
            <button type="button" class="btn btn-primary d-inline-flex align-items-center">
                <i class="fas fa-qrcode pe-2" aria-hidden="true"></i>
                Scan
            </button>
        </a>
    </div>
    <!-- Modal Content -->
    <div class="modal fade" id="ocr-modal" tabindex="-1" role="dialog" aria-labelledby="ocr-modal"
        aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h2 class="h6 modal-title">Edit RBI</h2>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" id="close-modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <!-- Form -->
                    <form method="post" id="ocr-form">
                        {% csrf_token %}

                        {% if contact_form.non_field_errors %}
                            <div class="alert alert-danger" role="alert">
                                {% for error in form.non_field_errors %}
                                    <p class="text-center">{{ error }}</p>
                                {% endfor %}
                            </div>
                        {% endif %}

                        {% for field in form %}
                            <div class="form-group mb-4">
                                {{ field.label_tag }}
                                {{ field }}
                                <small class="form-text text-muted d-block px-1">{{ field.help_text }}</small>
                                {% if field.errors %}
                                    <div class="badge m-0 bg-danger text-uppercase">{{ field.errors|striptags }}</div>
                                {% endif %}
                            </div>
                        {% endfor %}
                    </form>
                    <!-- End of Form -->
                </div>
                <div class="modal-footer">
                    <button type="submit" form="ocr-form" name="Save RBI Form" class="btn btn-secondary">
                        Save
                    </button>
                    <button type="button" class="btn btn-link text-gray-600 ms-auto" data-bs-dismiss="modal" id="cancel-modal">
                        Close
                    </button>
                </div>
            </div>
        </div>
    </div>
    <!-- End of Modal Content -->
{% endblock content %}
{% block table_content %}
    <thead class="table-dark">
        <tr>
            <th data-checkbox="true"></th>
            <th data-field="creation_date" data-halign="center" data-align="center" data-sortable="true" data-footer-formatter="totalTextFormatter" class="border-0">DATE CREATED</th>
            <th data-field="date_accomplished" data-halign="center" data-align="center" data-sortable="true" data-footer-formatter="totalNameFormatter">DATE ACCOMPLISHED</th>
            <th data-field="house_num" data-halign="center" data-align="center" data-sortable="true">HOUSE #</th>
            <th data-field="address" data-halign="center" data-align="center" data-sortable="true">ADDRESS</th>
            <!--<th data-field="street" data-halign="center" data-align="center" data-sortable="true">STREET</th>-->
            <th data-field="family_name" data-halign="center" data-align="center" data-sortable="true">FAMILY NAME</th>
        </tr>
    </thead>
    <tbody>
        {% for house in rbi %}
            <tr>
                <td></td>
                <td class="fw-bold">{{ house.creation_date|default:"None Provided" }}</td>
                <td>{{ house.date_accomplished|default:"None Provided" }}</td>
                <td>
                    <a href="{% url "ocr:detail" house.house_num %}" class="text-info text-decoration-underline">
                        {{ house.house_num|default:"None Provided" }}
                    </a>
                </td>
                <td>{{ house.address|default:"None Provided" }}</td>
                <!--<td>{{ house.street|default:"None Provided" }}</td>-->
                <td>{{ house.family_name|default:"None Provided" }}</td>
            </tr>
        {% endfor %}
    </tbody>
{% endblock %}

{% block template %}
    <template id="profileTemplate">
        <div class="col-4 mt-3">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-12 col-lg-8 col-md-6">
                            <h3 class="mb-0 text-truncated">%FAMILY_NAME%</h3>
                            <div class="row">
                                <div class="fw-extrabold mt-3">Address</div>
                                <p class="fs-6">%ADDRESS%</p>
                            </div>
                            <div class="row">
                                <!--
                                <div class="col col-md-auto">
                                    <div class="fw-extrabold w-auto">Street</div>
                                    <p>%STREET%</p>
                                </div>
                               -->
                                <div class="col">
                                    <div class="fw-extrabold text-nowrap">House Number</div>
                                    <p>%HOUSE_NUM%</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-12 col-lg-4 col-md-6 text-center">
                            <img id="proof-image" src="{{ default_image }}" alt="Profile Picture"
                                class="mx-auto img-thumbnail img-fluid"
                                style="height: 120px;">
                            <br>
                            <span id="house-image" class="fw-extrabold form-text">House Image</span>
                        </div>
                        <div class="col-12 col-lg-12 pt-5 d-flex flex-row-reverse">
                            <a class="btn btn-outline-info" href="%FAMILY_TREE%"
                                data-toggle="tooltip" data-placement="top" title="View Family Tree">
                                <span class="fas fa-house-user"></span>
                                Family Tree
                            </a>
                            <a class="btn btn-outline-tertiary" onclick="redirectToEdit('{% url "ocr:edit" house_num=0 %}', '%HOUSE_NUM%')"
                                data-toggle="tooltip" data-placement="top" title="Edit RBI">
                                <span class="fas fa-edit"></span>
                                Edit
                            </a>
                            <button class="btn btn-outline-danger remove" name="delete" onclick="actionButton('%HOUSE_NUM%', 'delete')"
                                data-toggle="tooltip" data-placement="top" title="Delete Account">
                                <span class="fas fa-trash"></span>
                                Delete
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </template>
{% endblock template %}

{% block scripts %}
    {{ block.super }}
    <script type="text/javascript">
        const editUrl = '{% url "ocr:edit" house_num=0 %}'
        const deleteUrl = '{% url "ocr:delete" house_num=0 %}'
    </script>
    <script src="{% static "/ocr/js/ocr.js" %}"></script>
    <script>
        {% if form.address.value is not None %}
            ocrModal.show()
        {% endif %}
        {% if form.errors %}
            ocrModal.show()
        {% endif %}
    </script>
{% endblock scripts %}